@DiscordApp_HostAddress = http://localhost:5187

### 1. Register User A
POST {{DiscordApp_HostAddress}}/api/users/register
Content-Type: application/json

{
  "email": "testuser2@example.com",
  "password": "Password123!",
  "username": "testname1",
  "role": "User"
}

###

### 2. Login User A
# @name login
POST {{DiscordApp_HostAddress}}/api/users/login
Content-Type: application/json

{
  "email": "testuser@example.com",
  "password": "Password123!"
}

###

@authToken ={{login.response.body.*}}

### 3. Search Users by Name Prefix (Paginated)
GET {{DiscordApp_HostAddress}}/api/users/search?query=test&pageNumber=1&pageSize=10
Authorization: Bearer {{authToken}}

###

### 4. Search Users by Name with exact Tag Prompt (e.g. "testname1#")
GET {{DiscordApp_HostAddress}}/api/users/search?query=testname1%23&pageNumber=1&pageSize=10
Authorization: Bearer {{authToken}}

###

### 5. Search Users by Name and Tag Prefix (e.g. "testname1#00")
GET {{DiscordApp_HostAddress}}/api/users/search?query=testname1%2300&pageNumber=1&pageSize=10
Authorization: Bearer {{authToken}}

###
### Test Invalid Search Query (Multiple Hash Characters)
GET {{DiscordApp_HostAddress}}/api/users/search?query=testnam%23%23e1%2300&pageNumber=1&pageSize=10
Authorization: Bearer {{authToken}}
###

### 6. Send Friend Request
POST {{DiscordApp_HostAddress}}/api/friend-requests/send
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "receiverId": "a5772d2e-d62e-48be-9c34-3ee3112c127b"
}

###

### 7. Get Incoming Pending Requests
GET {{DiscordApp_HostAddress}}/api/friend-requests/incoming
Authorization: Bearer {{authToken}}

###

### 8. Get Outgoing Pending Requests
GET {{DiscordApp_HostAddress}}/api/friend-requests/outgoing
Authorization: Bearer {{authToken}}

###

### 9. Accept Friend Request
POST {{DiscordApp_HostAddress}}/api/friend-requests/1/accept
Authorization: Bearer {{authToken}}

###

### 10. Decline/Cancel Friend Request
DELETE {{DiscordApp_HostAddress}}/api/friend-requests/2/decline
Authorization: Bearer {{authToken}}

###

### 11. Get Friends List
GET {{DiscordApp_HostAddress}}/api/friends
Authorization: Bearer {{authToken}}

###

### 12. Unfriend User
DELETE {{DiscordApp_HostAddress}}/api/friends/31809e2c-ecc5-4b87-96de-3e48765d25d4
Authorization: Bearer {{authToken}}

###